name: Testing workflow

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m this
        git tag
    - if: github.ref == 'refs/heads/main'
      run: |
        git tag -d tag_from_actions || true
        git push origin :refs/tags/tag_from_actions || true

        git tag tag_from_actions
        git push origin tag_from_actions
